
#this file has been generated by HexPartitionGenerator.py
         
from NoiseConfigs.noiseConfigGeneralAttribute import NoiseConfigGeneralAttribute
from NoiseConfigs.noiseConfig import NoiseConfig
from typing import Optional, Dict
from NoiseConfigs.utilsFunctions import UtilsFunc
import random


class Partitions:
    centerX: float
    centerY: float
    radius: float
    rainStatus: Optional[NoiseConfig.RainNoiseConfig]
    trafficStatus: Optional[NoiseConfig.TrafficNoiseConfig]
    urbanStatus: Optional[NoiseConfig.UrbanNoiseConfig]

    def __init__(self, centerX, centerY, radius, rainStatus, trafficStatus, urbanStatus):
        self.centerX = centerX
        self.centerY = centerY
        self.radius = radius
        self.rainStatus = rainStatus
        self.trafficStatus = trafficStatus
        self.urbanStatus = urbanStatus

    def update_traffic_status(self, traffic_statuses: Dict["Partitions", str]):
        new_status_str = traffic_statuses[self]
        self.trafficStatus = eval(new_status_str)

class Partition1(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 0.0
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition1.center_x, Partition1.center_y, 200, Partition1.rainStatus, Partition1.trafficStatus, Partition1.urbanStatus)


class Partition2(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 346.41016151377545
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition2.center_x, Partition2.center_y, 200, Partition2.rainStatus, Partition2.trafficStatus, Partition2.urbanStatus)


class Partition3(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 692.8203230275509
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition3.center_x, Partition3.center_y, 200, Partition3.rainStatus, Partition3.trafficStatus, Partition3.urbanStatus)


class Partition4(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1039.2304845413264
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition4.center_x, Partition4.center_y, 200, Partition4.rainStatus, Partition4.trafficStatus, Partition4.urbanStatus)


class Partition5(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1385.6406460551018
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition5.center_x, Partition5.center_y, 200, Partition5.rainStatus, Partition5.trafficStatus, Partition5.urbanStatus)


class Partition6(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1732.0508075688772
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition6.center_x, Partition6.center_y, 200, Partition6.rainStatus, Partition6.trafficStatus, Partition6.urbanStatus)


class Partition7(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2078.460969082653
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition7.center_x, Partition7.center_y, 200, Partition7.rainStatus, Partition7.trafficStatus, Partition7.urbanStatus)


class Partition8(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2424.871130596428
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition8.center_x, Partition8.center_y, 200, Partition8.rainStatus, Partition8.trafficStatus, Partition8.urbanStatus)


class Partition9(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2771.2812921102036
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition9.center_x, Partition9.center_y, 200, Partition9.rainStatus, Partition9.trafficStatus, Partition9.urbanStatus)


class Partition10(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3117.691453623979
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition10.center_x, Partition10.center_y, 200, Partition10.rainStatus, Partition10.trafficStatus, Partition10.urbanStatus)


class Partition11(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3464.1016151377544
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition11.center_x, Partition11.center_y, 200, Partition11.rainStatus, Partition11.trafficStatus, Partition11.urbanStatus)


class Partition12(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3810.51177665153
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition12.center_x, Partition12.center_y, 200, Partition12.rainStatus, Partition12.trafficStatus, Partition12.urbanStatus)


class Partition13(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 4156.921938165306
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition13.center_x, Partition13.center_y, 200, Partition13.rainStatus, Partition13.trafficStatus, Partition13.urbanStatus)


class Partition14(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4503.332099679081
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition14.center_x, Partition14.center_y, 200, Partition14.rainStatus, Partition14.trafficStatus, Partition14.urbanStatus)


class Partition15(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 173.20508075688772
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition15.center_x, Partition15.center_y, 200, Partition15.rainStatus, Partition15.trafficStatus, Partition15.urbanStatus)


class Partition16(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 519.6152422706632
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition16.center_x, Partition16.center_y, 200, Partition16.rainStatus, Partition16.trafficStatus, Partition16.urbanStatus)


class Partition17(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 866.0254037844386
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition17.center_x, Partition17.center_y, 200, Partition17.rainStatus, Partition17.trafficStatus, Partition17.urbanStatus)


class Partition18(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1212.4355652982142
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition18.center_x, Partition18.center_y, 200, Partition18.rainStatus, Partition18.trafficStatus, Partition18.urbanStatus)


class Partition19(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1558.8457268119896
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition19.center_x, Partition19.center_y, 200, Partition19.rainStatus, Partition19.trafficStatus, Partition19.urbanStatus)


class Partition20(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1905.255888325765
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition20.center_x, Partition20.center_y, 200, Partition20.rainStatus, Partition20.trafficStatus, Partition20.urbanStatus)


class Partition21(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2251.6660498395404
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition21.center_x, Partition21.center_y, 200, Partition21.rainStatus, Partition21.trafficStatus, Partition21.urbanStatus)


class Partition22(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2598.0762113533156
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition22.center_x, Partition22.center_y, 200, Partition22.rainStatus, Partition22.trafficStatus, Partition22.urbanStatus)


class Partition23(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2944.486372867091
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition23.center_x, Partition23.center_y, 200, Partition23.rainStatus, Partition23.trafficStatus, Partition23.urbanStatus)


class Partition24(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3290.896534380867
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition24.center_x, Partition24.center_y, 200, Partition24.rainStatus, Partition24.trafficStatus, Partition24.urbanStatus)


class Partition25(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3637.306695894642
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition25.center_x, Partition25.center_y, 200, Partition25.rainStatus, Partition25.trafficStatus, Partition25.urbanStatus)


class Partition26(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3983.7168574084176
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition26.center_x, Partition26.center_y, 200, Partition26.rainStatus, Partition26.trafficStatus, Partition26.urbanStatus)


class Partition27(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4330.127018922193
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition27.center_x, Partition27.center_y, 200, Partition27.rainStatus, Partition27.trafficStatus, Partition27.urbanStatus)


class Partition28(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4676.537180435968
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition28.center_x, Partition28.center_y, 200, Partition28.rainStatus, Partition28.trafficStatus, Partition28.urbanStatus)


class Partition29(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 0.0
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition29.center_x, Partition29.center_y, 200, Partition29.rainStatus, Partition29.trafficStatus, Partition29.urbanStatus)


class Partition30(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 346.41016151377545
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition30.center_x, Partition30.center_y, 200, Partition30.rainStatus, Partition30.trafficStatus, Partition30.urbanStatus)


class Partition31(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 692.8203230275509
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition31.center_x, Partition31.center_y, 200, Partition31.rainStatus, Partition31.trafficStatus, Partition31.urbanStatus)


class Partition32(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1039.2304845413264
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition32.center_x, Partition32.center_y, 200, Partition32.rainStatus, Partition32.trafficStatus, Partition32.urbanStatus)


class Partition33(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1385.6406460551018
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition33.center_x, Partition33.center_y, 200, Partition33.rainStatus, Partition33.trafficStatus, Partition33.urbanStatus)


class Partition34(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1732.0508075688772
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition34.center_x, Partition34.center_y, 200, Partition34.rainStatus, Partition34.trafficStatus, Partition34.urbanStatus)


class Partition35(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2078.460969082653
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition35.center_x, Partition35.center_y, 200, Partition35.rainStatus, Partition35.trafficStatus, Partition35.urbanStatus)


class Partition36(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2424.871130596428
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition36.center_x, Partition36.center_y, 200, Partition36.rainStatus, Partition36.trafficStatus, Partition36.urbanStatus)


class Partition37(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2771.2812921102036
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition37.center_x, Partition37.center_y, 200, Partition37.rainStatus, Partition37.trafficStatus, Partition37.urbanStatus)


class Partition38(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 3117.691453623979
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition38.center_x, Partition38.center_y, 200, Partition38.rainStatus, Partition38.trafficStatus, Partition38.urbanStatus)


class Partition39(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3464.1016151377544
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition39.center_x, Partition39.center_y, 200, Partition39.rainStatus, Partition39.trafficStatus, Partition39.urbanStatus)


class Partition40(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3810.51177665153
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition40.center_x, Partition40.center_y, 200, Partition40.rainStatus, Partition40.trafficStatus, Partition40.urbanStatus)


class Partition41(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4156.921938165306
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition41.center_x, Partition41.center_y, 200, Partition41.rainStatus, Partition41.trafficStatus, Partition41.urbanStatus)


class Partition42(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4503.332099679081
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition42.center_x, Partition42.center_y, 200, Partition42.rainStatus, Partition42.trafficStatus, Partition42.urbanStatus)


class Partition43(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 173.20508075688772
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition43.center_x, Partition43.center_y, 200, Partition43.rainStatus, Partition43.trafficStatus, Partition43.urbanStatus)


class Partition44(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 519.6152422706632
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition44.center_x, Partition44.center_y, 200, Partition44.rainStatus, Partition44.trafficStatus, Partition44.urbanStatus)


class Partition45(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 866.0254037844386
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition45.center_x, Partition45.center_y, 200, Partition45.rainStatus, Partition45.trafficStatus, Partition45.urbanStatus)


class Partition46(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1212.4355652982142
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition46.center_x, Partition46.center_y, 200, Partition46.rainStatus, Partition46.trafficStatus, Partition46.urbanStatus)


class Partition47(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1558.8457268119896
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition47.center_x, Partition47.center_y, 200, Partition47.rainStatus, Partition47.trafficStatus, Partition47.urbanStatus)


class Partition48(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1905.255888325765
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition48.center_x, Partition48.center_y, 200, Partition48.rainStatus, Partition48.trafficStatus, Partition48.urbanStatus)


class Partition49(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2251.6660498395404
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition49.center_x, Partition49.center_y, 200, Partition49.rainStatus, Partition49.trafficStatus, Partition49.urbanStatus)


class Partition50(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2598.0762113533156
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition50.center_x, Partition50.center_y, 200, Partition50.rainStatus, Partition50.trafficStatus, Partition50.urbanStatus)


class Partition51(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2944.486372867091
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition51.center_x, Partition51.center_y, 200, Partition51.rainStatus, Partition51.trafficStatus, Partition51.urbanStatus)


class Partition52(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3290.896534380867
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition52.center_x, Partition52.center_y, 200, Partition52.rainStatus, Partition52.trafficStatus, Partition52.urbanStatus)


class Partition53(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3637.306695894642
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition53.center_x, Partition53.center_y, 200, Partition53.rainStatus, Partition53.trafficStatus, Partition53.urbanStatus)


class Partition54(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3983.7168574084176
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition54.center_x, Partition54.center_y, 200, Partition54.rainStatus, Partition54.trafficStatus, Partition54.urbanStatus)


class Partition55(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4330.127018922193
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition55.center_x, Partition55.center_y, 200, Partition55.rainStatus, Partition55.trafficStatus, Partition55.urbanStatus)


class Partition56(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4676.537180435968
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition56.center_x, Partition56.center_y, 200, Partition56.rainStatus, Partition56.trafficStatus, Partition56.urbanStatus)


class Partition57(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 0.0
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition57.center_x, Partition57.center_y, 200, Partition57.rainStatus, Partition57.trafficStatus, Partition57.urbanStatus)


class Partition58(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 346.41016151377545
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition58.center_x, Partition58.center_y, 200, Partition58.rainStatus, Partition58.trafficStatus, Partition58.urbanStatus)


class Partition59(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 692.8203230275509
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition59.center_x, Partition59.center_y, 200, Partition59.rainStatus, Partition59.trafficStatus, Partition59.urbanStatus)


class Partition60(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1039.2304845413264
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition60.center_x, Partition60.center_y, 200, Partition60.rainStatus, Partition60.trafficStatus, Partition60.urbanStatus)


class Partition61(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1385.6406460551018
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition61.center_x, Partition61.center_y, 200, Partition61.rainStatus, Partition61.trafficStatus, Partition61.urbanStatus)


class Partition62(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1732.0508075688772
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition62.center_x, Partition62.center_y, 200, Partition62.rainStatus, Partition62.trafficStatus, Partition62.urbanStatus)


class Partition63(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2078.460969082653
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition63.center_x, Partition63.center_y, 200, Partition63.rainStatus, Partition63.trafficStatus, Partition63.urbanStatus)


class Partition64(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2424.871130596428
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition64.center_x, Partition64.center_y, 200, Partition64.rainStatus, Partition64.trafficStatus, Partition64.urbanStatus)


class Partition65(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2771.2812921102036
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition65.center_x, Partition65.center_y, 200, Partition65.rainStatus, Partition65.trafficStatus, Partition65.urbanStatus)


class Partition66(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3117.691453623979
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition66.center_x, Partition66.center_y, 200, Partition66.rainStatus, Partition66.trafficStatus, Partition66.urbanStatus)


class Partition67(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3464.1016151377544
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition67.center_x, Partition67.center_y, 200, Partition67.rainStatus, Partition67.trafficStatus, Partition67.urbanStatus)


class Partition68(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3810.51177665153
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition68.center_x, Partition68.center_y, 200, Partition68.rainStatus, Partition68.trafficStatus, Partition68.urbanStatus)


class Partition69(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4156.921938165306
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition69.center_x, Partition69.center_y, 200, Partition69.rainStatus, Partition69.trafficStatus, Partition69.urbanStatus)


class Partition70(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4503.332099679081
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition70.center_x, Partition70.center_y, 200, Partition70.rainStatus, Partition70.trafficStatus, Partition70.urbanStatus)


class Partition71(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 173.20508075688772
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition71.center_x, Partition71.center_y, 200, Partition71.rainStatus, Partition71.trafficStatus, Partition71.urbanStatus)


class Partition72(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 519.6152422706632
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition72.center_x, Partition72.center_y, 200, Partition72.rainStatus, Partition72.trafficStatus, Partition72.urbanStatus)


class Partition73(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 866.0254037844386
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition73.center_x, Partition73.center_y, 200, Partition73.rainStatus, Partition73.trafficStatus, Partition73.urbanStatus)


class Partition74(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1212.4355652982142
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition74.center_x, Partition74.center_y, 200, Partition74.rainStatus, Partition74.trafficStatus, Partition74.urbanStatus)


class Partition75(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1558.8457268119896
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition75.center_x, Partition75.center_y, 200, Partition75.rainStatus, Partition75.trafficStatus, Partition75.urbanStatus)


class Partition76(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1905.255888325765
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition76.center_x, Partition76.center_y, 200, Partition76.rainStatus, Partition76.trafficStatus, Partition76.urbanStatus)


class Partition77(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2251.6660498395404
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition77.center_x, Partition77.center_y, 200, Partition77.rainStatus, Partition77.trafficStatus, Partition77.urbanStatus)


class Partition78(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2598.0762113533156
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition78.center_x, Partition78.center_y, 200, Partition78.rainStatus, Partition78.trafficStatus, Partition78.urbanStatus)


class Partition79(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2944.486372867091
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition79.center_x, Partition79.center_y, 200, Partition79.rainStatus, Partition79.trafficStatus, Partition79.urbanStatus)


class Partition80(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3290.896534380867
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition80.center_x, Partition80.center_y, 200, Partition80.rainStatus, Partition80.trafficStatus, Partition80.urbanStatus)


class Partition81(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3637.306695894642
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition81.center_x, Partition81.center_y, 200, Partition81.rainStatus, Partition81.trafficStatus, Partition81.urbanStatus)


class Partition82(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3983.7168574084176
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition82.center_x, Partition82.center_y, 200, Partition82.rainStatus, Partition82.trafficStatus, Partition82.urbanStatus)


class Partition83(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4330.127018922193
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition83.center_x, Partition83.center_y, 200, Partition83.rainStatus, Partition83.trafficStatus, Partition83.urbanStatus)


class Partition84(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4676.537180435968
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition84.center_x, Partition84.center_y, 200, Partition84.rainStatus, Partition84.trafficStatus, Partition84.urbanStatus)


class Partition85(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 0.0
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition85.center_x, Partition85.center_y, 200, Partition85.rainStatus, Partition85.trafficStatus, Partition85.urbanStatus)


class Partition86(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 346.41016151377545
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition86.center_x, Partition86.center_y, 200, Partition86.rainStatus, Partition86.trafficStatus, Partition86.urbanStatus)


class Partition87(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 692.8203230275509
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition87.center_x, Partition87.center_y, 200, Partition87.rainStatus, Partition87.trafficStatus, Partition87.urbanStatus)


class Partition88(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1039.2304845413264
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition88.center_x, Partition88.center_y, 200, Partition88.rainStatus, Partition88.trafficStatus, Partition88.urbanStatus)


class Partition89(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1385.6406460551018
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition89.center_x, Partition89.center_y, 200, Partition89.rainStatus, Partition89.trafficStatus, Partition89.urbanStatus)


class Partition90(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1732.0508075688772
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition90.center_x, Partition90.center_y, 200, Partition90.rainStatus, Partition90.trafficStatus, Partition90.urbanStatus)


class Partition91(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2078.460969082653
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition91.center_x, Partition91.center_y, 200, Partition91.rainStatus, Partition91.trafficStatus, Partition91.urbanStatus)


class Partition92(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2424.871130596428
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition92.center_x, Partition92.center_y, 200, Partition92.rainStatus, Partition92.trafficStatus, Partition92.urbanStatus)


class Partition93(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2771.2812921102036
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition93.center_x, Partition93.center_y, 200, Partition93.rainStatus, Partition93.trafficStatus, Partition93.urbanStatus)


class Partition94(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3117.691453623979
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition94.center_x, Partition94.center_y, 200, Partition94.rainStatus, Partition94.trafficStatus, Partition94.urbanStatus)


class Partition95(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 3464.1016151377544
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition95.center_x, Partition95.center_y, 200, Partition95.rainStatus, Partition95.trafficStatus, Partition95.urbanStatus)


class Partition96(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 3810.51177665153
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition96.center_x, Partition96.center_y, 200, Partition96.rainStatus, Partition96.trafficStatus, Partition96.urbanStatus)


class Partition97(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 4156.921938165306
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition97.center_x, Partition97.center_y, 200, Partition97.rainStatus, Partition97.trafficStatus, Partition97.urbanStatus)


class Partition98(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 4503.332099679081
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition98.center_x, Partition98.center_y, 200, Partition98.rainStatus, Partition98.trafficStatus, Partition98.urbanStatus)


class Partition99(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 173.20508075688772
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition99.center_x, Partition99.center_y, 200, Partition99.rainStatus, Partition99.trafficStatus, Partition99.urbanStatus)


class Partition100(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 519.6152422706632
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition100.center_x, Partition100.center_y, 200, Partition100.rainStatus, Partition100.trafficStatus, Partition100.urbanStatus)


class Partition101(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 866.0254037844386
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition101.center_x, Partition101.center_y, 200, Partition101.rainStatus, Partition101.trafficStatus, Partition101.urbanStatus)


class Partition102(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1212.4355652982142
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition102.center_x, Partition102.center_y, 200, Partition102.rainStatus, Partition102.trafficStatus, Partition102.urbanStatus)


class Partition103(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1558.8457268119896
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition103.center_x, Partition103.center_y, 200, Partition103.rainStatus, Partition103.trafficStatus, Partition103.urbanStatus)


class Partition104(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1905.255888325765
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition104.center_x, Partition104.center_y, 200, Partition104.rainStatus, Partition104.trafficStatus, Partition104.urbanStatus)


class Partition105(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2251.6660498395404
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition105.center_x, Partition105.center_y, 200, Partition105.rainStatus, Partition105.trafficStatus, Partition105.urbanStatus)


class Partition106(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2598.0762113533156
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition106.center_x, Partition106.center_y, 200, Partition106.rainStatus, Partition106.trafficStatus, Partition106.urbanStatus)


class Partition107(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2944.486372867091
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition107.center_x, Partition107.center_y, 200, Partition107.rainStatus, Partition107.trafficStatus, Partition107.urbanStatus)


class Partition108(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3290.896534380867
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition108.center_x, Partition108.center_y, 200, Partition108.rainStatus, Partition108.trafficStatus, Partition108.urbanStatus)


class Partition109(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3637.306695894642
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition109.center_x, Partition109.center_y, 200, Partition109.rainStatus, Partition109.trafficStatus, Partition109.urbanStatus)


class Partition110(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3983.7168574084176
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition110.center_x, Partition110.center_y, 200, Partition110.rainStatus, Partition110.trafficStatus, Partition110.urbanStatus)


class Partition111(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4330.127018922193
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition111.center_x, Partition111.center_y, 200, Partition111.rainStatus, Partition111.trafficStatus, Partition111.urbanStatus)


class Partition112(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 4676.537180435968
    center_y = 2100.0

    def __init__(self):
        super().__init__(Partition112.center_x, Partition112.center_y, 200, Partition112.rainStatus, Partition112.trafficStatus, Partition112.urbanStatus)


class Partition113(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 0.0
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition113.center_x, Partition113.center_y, 200, Partition113.rainStatus, Partition113.trafficStatus, Partition113.urbanStatus)


class Partition114(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 346.41016151377545
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition114.center_x, Partition114.center_y, 200, Partition114.rainStatus, Partition114.trafficStatus, Partition114.urbanStatus)


class Partition115(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 692.8203230275509
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition115.center_x, Partition115.center_y, 200, Partition115.rainStatus, Partition115.trafficStatus, Partition115.urbanStatus)


class Partition116(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1039.2304845413264
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition116.center_x, Partition116.center_y, 200, Partition116.rainStatus, Partition116.trafficStatus, Partition116.urbanStatus)


class Partition117(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1385.6406460551018
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition117.center_x, Partition117.center_y, 200, Partition117.rainStatus, Partition117.trafficStatus, Partition117.urbanStatus)


class Partition118(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1732.0508075688772
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition118.center_x, Partition118.center_y, 200, Partition118.rainStatus, Partition118.trafficStatus, Partition118.urbanStatus)


class Partition119(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2078.460969082653
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition119.center_x, Partition119.center_y, 200, Partition119.rainStatus, Partition119.trafficStatus, Partition119.urbanStatus)


class Partition120(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2424.871130596428
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition120.center_x, Partition120.center_y, 200, Partition120.rainStatus, Partition120.trafficStatus, Partition120.urbanStatus)


class Partition121(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2771.2812921102036
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition121.center_x, Partition121.center_y, 200, Partition121.rainStatus, Partition121.trafficStatus, Partition121.urbanStatus)


class Partition122(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3117.691453623979
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition122.center_x, Partition122.center_y, 200, Partition122.rainStatus, Partition122.trafficStatus, Partition122.urbanStatus)


class Partition123(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3464.1016151377544
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition123.center_x, Partition123.center_y, 200, Partition123.rainStatus, Partition123.trafficStatus, Partition123.urbanStatus)


class Partition124(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3810.51177665153
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition124.center_x, Partition124.center_y, 200, Partition124.rainStatus, Partition124.trafficStatus, Partition124.urbanStatus)


class Partition125(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4156.921938165306
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition125.center_x, Partition125.center_y, 200, Partition125.rainStatus, Partition125.trafficStatus, Partition125.urbanStatus)


class Partition126(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4503.332099679081
    center_y = 2400.0

    def __init__(self):
        super().__init__(Partition126.center_x, Partition126.center_y, 200, Partition126.rainStatus, Partition126.trafficStatus, Partition126.urbanStatus)


class Partition127(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 173.20508075688772
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition127.center_x, Partition127.center_y, 200, Partition127.rainStatus, Partition127.trafficStatus, Partition127.urbanStatus)


class Partition128(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 519.6152422706632
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition128.center_x, Partition128.center_y, 200, Partition128.rainStatus, Partition128.trafficStatus, Partition128.urbanStatus)


class Partition129(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 866.0254037844386
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition129.center_x, Partition129.center_y, 200, Partition129.rainStatus, Partition129.trafficStatus, Partition129.urbanStatus)


class Partition130(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1212.4355652982142
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition130.center_x, Partition130.center_y, 200, Partition130.rainStatus, Partition130.trafficStatus, Partition130.urbanStatus)


class Partition131(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1558.8457268119896
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition131.center_x, Partition131.center_y, 200, Partition131.rainStatus, Partition131.trafficStatus, Partition131.urbanStatus)


class Partition132(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1905.255888325765
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition132.center_x, Partition132.center_y, 200, Partition132.rainStatus, Partition132.trafficStatus, Partition132.urbanStatus)


class Partition133(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2251.6660498395404
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition133.center_x, Partition133.center_y, 200, Partition133.rainStatus, Partition133.trafficStatus, Partition133.urbanStatus)


class Partition134(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2598.0762113533156
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition134.center_x, Partition134.center_y, 200, Partition134.rainStatus, Partition134.trafficStatus, Partition134.urbanStatus)


class Partition135(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2944.486372867091
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition135.center_x, Partition135.center_y, 200, Partition135.rainStatus, Partition135.trafficStatus, Partition135.urbanStatus)


class Partition136(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3290.896534380867
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition136.center_x, Partition136.center_y, 200, Partition136.rainStatus, Partition136.trafficStatus, Partition136.urbanStatus)


class Partition137(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 3637.306695894642
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition137.center_x, Partition137.center_y, 200, Partition137.rainStatus, Partition137.trafficStatus, Partition137.urbanStatus)


class Partition138(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3983.7168574084176
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition138.center_x, Partition138.center_y, 200, Partition138.rainStatus, Partition138.trafficStatus, Partition138.urbanStatus)


class Partition139(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4330.127018922193
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition139.center_x, Partition139.center_y, 200, Partition139.rainStatus, Partition139.trafficStatus, Partition139.urbanStatus)


class Partition140(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4676.537180435968
    center_y = 2700.0

    def __init__(self):
        super().__init__(Partition140.center_x, Partition140.center_y, 200, Partition140.rainStatus, Partition140.trafficStatus, Partition140.urbanStatus)


class Partition141(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 0.0
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition141.center_x, Partition141.center_y, 200, Partition141.rainStatus, Partition141.trafficStatus, Partition141.urbanStatus)


class Partition142(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 346.41016151377545
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition142.center_x, Partition142.center_y, 200, Partition142.rainStatus, Partition142.trafficStatus, Partition142.urbanStatus)


class Partition143(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 692.8203230275509
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition143.center_x, Partition143.center_y, 200, Partition143.rainStatus, Partition143.trafficStatus, Partition143.urbanStatus)


class Partition144(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1039.2304845413264
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition144.center_x, Partition144.center_y, 200, Partition144.rainStatus, Partition144.trafficStatus, Partition144.urbanStatus)


class Partition145(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1385.6406460551018
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition145.center_x, Partition145.center_y, 200, Partition145.rainStatus, Partition145.trafficStatus, Partition145.urbanStatus)


class Partition146(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1732.0508075688772
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition146.center_x, Partition146.center_y, 200, Partition146.rainStatus, Partition146.trafficStatus, Partition146.urbanStatus)


class Partition147(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2078.460969082653
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition147.center_x, Partition147.center_y, 200, Partition147.rainStatus, Partition147.trafficStatus, Partition147.urbanStatus)


class Partition148(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2424.871130596428
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition148.center_x, Partition148.center_y, 200, Partition148.rainStatus, Partition148.trafficStatus, Partition148.urbanStatus)


class Partition149(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2771.2812921102036
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition149.center_x, Partition149.center_y, 200, Partition149.rainStatus, Partition149.trafficStatus, Partition149.urbanStatus)


class Partition150(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3117.691453623979
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition150.center_x, Partition150.center_y, 200, Partition150.rainStatus, Partition150.trafficStatus, Partition150.urbanStatus)


class Partition151(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 3464.1016151377544
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition151.center_x, Partition151.center_y, 200, Partition151.rainStatus, Partition151.trafficStatus, Partition151.urbanStatus)


class Partition152(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3810.51177665153
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition152.center_x, Partition152.center_y, 200, Partition152.rainStatus, Partition152.trafficStatus, Partition152.urbanStatus)


class Partition153(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4156.921938165306
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition153.center_x, Partition153.center_y, 200, Partition153.rainStatus, Partition153.trafficStatus, Partition153.urbanStatus)


class Partition154(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 4503.332099679081
    center_y = 3000.0

    def __init__(self):
        super().__init__(Partition154.center_x, Partition154.center_y, 200, Partition154.rainStatus, Partition154.trafficStatus, Partition154.urbanStatus)


class Partition155(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 173.20508075688772
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition155.center_x, Partition155.center_y, 200, Partition155.rainStatus, Partition155.trafficStatus, Partition155.urbanStatus)


class Partition156(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 519.6152422706632
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition156.center_x, Partition156.center_y, 200, Partition156.rainStatus, Partition156.trafficStatus, Partition156.urbanStatus)


class Partition157(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 866.0254037844386
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition157.center_x, Partition157.center_y, 200, Partition157.rainStatus, Partition157.trafficStatus, Partition157.urbanStatus)


class Partition158(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1212.4355652982142
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition158.center_x, Partition158.center_y, 200, Partition158.rainStatus, Partition158.trafficStatus, Partition158.urbanStatus)


class Partition159(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1558.8457268119896
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition159.center_x, Partition159.center_y, 200, Partition159.rainStatus, Partition159.trafficStatus, Partition159.urbanStatus)


class Partition160(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1905.255888325765
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition160.center_x, Partition160.center_y, 200, Partition160.rainStatus, Partition160.trafficStatus, Partition160.urbanStatus)


class Partition161(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2251.6660498395404
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition161.center_x, Partition161.center_y, 200, Partition161.rainStatus, Partition161.trafficStatus, Partition161.urbanStatus)


class Partition162(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2598.0762113533156
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition162.center_x, Partition162.center_y, 200, Partition162.rainStatus, Partition162.trafficStatus, Partition162.urbanStatus)


class Partition163(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2944.486372867091
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition163.center_x, Partition163.center_y, 200, Partition163.rainStatus, Partition163.trafficStatus, Partition163.urbanStatus)


class Partition164(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3290.896534380867
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition164.center_x, Partition164.center_y, 200, Partition164.rainStatus, Partition164.trafficStatus, Partition164.urbanStatus)


class Partition165(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3637.306695894642
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition165.center_x, Partition165.center_y, 200, Partition165.rainStatus, Partition165.trafficStatus, Partition165.urbanStatus)


class Partition166(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 3983.7168574084176
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition166.center_x, Partition166.center_y, 200, Partition166.rainStatus, Partition166.trafficStatus, Partition166.urbanStatus)


class Partition167(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4330.127018922193
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition167.center_x, Partition167.center_y, 200, Partition167.rainStatus, Partition167.trafficStatus, Partition167.urbanStatus)


class Partition168(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 4676.537180435968
    center_y = 3300.0

    def __init__(self):
        super().__init__(Partition168.center_x, Partition168.center_y, 200, Partition168.rainStatus, Partition168.trafficStatus, Partition168.urbanStatus)


class Partition169(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 0.0
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition169.center_x, Partition169.center_y, 200, Partition169.rainStatus, Partition169.trafficStatus, Partition169.urbanStatus)


class Partition170(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 346.41016151377545
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition170.center_x, Partition170.center_y, 200, Partition170.rainStatus, Partition170.trafficStatus, Partition170.urbanStatus)


class Partition171(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 692.8203230275509
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition171.center_x, Partition171.center_y, 200, Partition171.rainStatus, Partition171.trafficStatus, Partition171.urbanStatus)


class Partition172(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1039.2304845413264
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition172.center_x, Partition172.center_y, 200, Partition172.rainStatus, Partition172.trafficStatus, Partition172.urbanStatus)


class Partition173(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1385.6406460551018
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition173.center_x, Partition173.center_y, 200, Partition173.rainStatus, Partition173.trafficStatus, Partition173.urbanStatus)


class Partition174(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1732.0508075688772
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition174.center_x, Partition174.center_y, 200, Partition174.rainStatus, Partition174.trafficStatus, Partition174.urbanStatus)


class Partition175(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2078.460969082653
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition175.center_x, Partition175.center_y, 200, Partition175.rainStatus, Partition175.trafficStatus, Partition175.urbanStatus)


class Partition176(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2424.871130596428
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition176.center_x, Partition176.center_y, 200, Partition176.rainStatus, Partition176.trafficStatus, Partition176.urbanStatus)


class Partition177(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2771.2812921102036
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition177.center_x, Partition177.center_y, 200, Partition177.rainStatus, Partition177.trafficStatus, Partition177.urbanStatus)


class Partition178(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3117.691453623979
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition178.center_x, Partition178.center_y, 200, Partition178.rainStatus, Partition178.trafficStatus, Partition178.urbanStatus)


class Partition179(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 3464.1016151377544
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition179.center_x, Partition179.center_y, 200, Partition179.rainStatus, Partition179.trafficStatus, Partition179.urbanStatus)


class Partition180(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 3810.51177665153
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition180.center_x, Partition180.center_y, 200, Partition180.rainStatus, Partition180.trafficStatus, Partition180.urbanStatus)


class Partition181(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 4156.921938165306
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition181.center_x, Partition181.center_y, 200, Partition181.rainStatus, Partition181.trafficStatus, Partition181.urbanStatus)


class Partition182(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 4503.332099679081
    center_y = 3600.0

    def __init__(self):
        super().__init__(Partition182.center_x, Partition182.center_y, 200, Partition182.rainStatus, Partition182.trafficStatus, Partition182.urbanStatus)
