
#this file has been generated by HexPartitionGenerator.py
         
from NoiseConfigs.noiseConfigGeneralAttribute import NoiseConfigGeneralAttribute
from NoiseConfigs.noiseConfig import NoiseConfig
from typing import Optional, Dict
from NoiseConfigs.utilsFunctions import UtilsFunc
import random


class Partitions:
    centerX: float
    centerY: float
    radius: float
    rainStatus: Optional[NoiseConfig.RainNoiseConfig]
    trafficStatus: Optional[NoiseConfig.TrafficNoiseConfig]
    urbanStatus: Optional[NoiseConfig.UrbanNoiseConfig]

    def __init__(self, centerX, centerY, radius, rainStatus, trafficStatus, urbanStatus):
        self.centerX = centerX
        self.centerY = centerY
        self.radius = radius
        self.rainStatus = rainStatus
        self.trafficStatus = trafficStatus
        self.urbanStatus = urbanStatus

    def update_traffic_status(self, traffic_statuses: Dict["Partitions", str]):
        new_status_str = traffic_statuses[self]
        self.trafficStatus = eval(new_status_str)

class Partition1(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 0.0
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition1.center_x, Partition1.center_y, 200, Partition1.rainStatus, Partition1.trafficStatus, Partition1.urbanStatus)


class Partition2(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 346.41016151377545
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition2.center_x, Partition2.center_y, 200, Partition2.rainStatus, Partition2.trafficStatus, Partition2.urbanStatus)


class Partition3(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 692.8203230275509
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition3.center_x, Partition3.center_y, 200, Partition3.rainStatus, Partition3.trafficStatus, Partition3.urbanStatus)


class Partition4(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1039.2304845413264
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition4.center_x, Partition4.center_y, 200, Partition4.rainStatus, Partition4.trafficStatus, Partition4.urbanStatus)


class Partition5(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1385.6406460551018
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition5.center_x, Partition5.center_y, 200, Partition5.rainStatus, Partition5.trafficStatus, Partition5.urbanStatus)


class Partition6(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1732.0508075688772
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition6.center_x, Partition6.center_y, 200, Partition6.rainStatus, Partition6.trafficStatus, Partition6.urbanStatus)


class Partition7(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2078.460969082653
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition7.center_x, Partition7.center_y, 200, Partition7.rainStatus, Partition7.trafficStatus, Partition7.urbanStatus)


class Partition8(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2424.871130596428
    center_y = 0.0

    def __init__(self):
        super().__init__(Partition8.center_x, Partition8.center_y, 200, Partition8.rainStatus, Partition8.trafficStatus, Partition8.urbanStatus)


class Partition9(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 173.20508075688772
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition9.center_x, Partition9.center_y, 200, Partition9.rainStatus, Partition9.trafficStatus, Partition9.urbanStatus)


class Partition10(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 519.6152422706632
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition10.center_x, Partition10.center_y, 200, Partition10.rainStatus, Partition10.trafficStatus, Partition10.urbanStatus)


class Partition11(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 866.0254037844386
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition11.center_x, Partition11.center_y, 200, Partition11.rainStatus, Partition11.trafficStatus, Partition11.urbanStatus)


class Partition12(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1212.4355652982142
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition12.center_x, Partition12.center_y, 200, Partition12.rainStatus, Partition12.trafficStatus, Partition12.urbanStatus)


class Partition13(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1558.8457268119896
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition13.center_x, Partition13.center_y, 200, Partition13.rainStatus, Partition13.trafficStatus, Partition13.urbanStatus)


class Partition14(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1905.255888325765
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition14.center_x, Partition14.center_y, 200, Partition14.rainStatus, Partition14.trafficStatus, Partition14.urbanStatus)


class Partition15(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2251.6660498395404
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition15.center_x, Partition15.center_y, 200, Partition15.rainStatus, Partition15.trafficStatus, Partition15.urbanStatus)


class Partition16(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2598.0762113533156
    center_y = 300.0

    def __init__(self):
        super().__init__(Partition16.center_x, Partition16.center_y, 200, Partition16.rainStatus, Partition16.trafficStatus, Partition16.urbanStatus)


class Partition17(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 0.0
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition17.center_x, Partition17.center_y, 200, Partition17.rainStatus, Partition17.trafficStatus, Partition17.urbanStatus)


class Partition18(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 346.41016151377545
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition18.center_x, Partition18.center_y, 200, Partition18.rainStatus, Partition18.trafficStatus, Partition18.urbanStatus)


class Partition19(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 692.8203230275509
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition19.center_x, Partition19.center_y, 200, Partition19.rainStatus, Partition19.trafficStatus, Partition19.urbanStatus)


class Partition20(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1039.2304845413264
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition20.center_x, Partition20.center_y, 200, Partition20.rainStatus, Partition20.trafficStatus, Partition20.urbanStatus)


class Partition21(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1385.6406460551018
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition21.center_x, Partition21.center_y, 200, Partition21.rainStatus, Partition21.trafficStatus, Partition21.urbanStatus)


class Partition22(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1732.0508075688772
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition22.center_x, Partition22.center_y, 200, Partition22.rainStatus, Partition22.trafficStatus, Partition22.urbanStatus)


class Partition23(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2078.460969082653
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition23.center_x, Partition23.center_y, 200, Partition23.rainStatus, Partition23.trafficStatus, Partition23.urbanStatus)


class Partition24(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2424.871130596428
    center_y = 600.0

    def __init__(self):
        super().__init__(Partition24.center_x, Partition24.center_y, 200, Partition24.rainStatus, Partition24.trafficStatus, Partition24.urbanStatus)


class Partition25(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 173.20508075688772
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition25.center_x, Partition25.center_y, 200, Partition25.rainStatus, Partition25.trafficStatus, Partition25.urbanStatus)


class Partition26(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 519.6152422706632
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition26.center_x, Partition26.center_y, 200, Partition26.rainStatus, Partition26.trafficStatus, Partition26.urbanStatus)


class Partition27(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 866.0254037844386
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition27.center_x, Partition27.center_y, 200, Partition27.rainStatus, Partition27.trafficStatus, Partition27.urbanStatus)


class Partition28(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1212.4355652982142
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition28.center_x, Partition28.center_y, 200, Partition28.rainStatus, Partition28.trafficStatus, Partition28.urbanStatus)


class Partition29(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1558.8457268119896
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition29.center_x, Partition29.center_y, 200, Partition29.rainStatus, Partition29.trafficStatus, Partition29.urbanStatus)


class Partition30(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1905.255888325765
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition30.center_x, Partition30.center_y, 200, Partition30.rainStatus, Partition30.trafficStatus, Partition30.urbanStatus)


class Partition31(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2251.6660498395404
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition31.center_x, Partition31.center_y, 200, Partition31.rainStatus, Partition31.trafficStatus, Partition31.urbanStatus)


class Partition32(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2598.0762113533156
    center_y = 900.0

    def __init__(self):
        super().__init__(Partition32.center_x, Partition32.center_y, 200, Partition32.rainStatus, Partition32.trafficStatus, Partition32.urbanStatus)


class Partition33(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 0.0
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition33.center_x, Partition33.center_y, 200, Partition33.rainStatus, Partition33.trafficStatus, Partition33.urbanStatus)


class Partition34(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 346.41016151377545
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition34.center_x, Partition34.center_y, 200, Partition34.rainStatus, Partition34.trafficStatus, Partition34.urbanStatus)


class Partition35(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 692.8203230275509
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition35.center_x, Partition35.center_y, 200, Partition35.rainStatus, Partition35.trafficStatus, Partition35.urbanStatus)


class Partition36(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 1039.2304845413264
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition36.center_x, Partition36.center_y, 200, Partition36.rainStatus, Partition36.trafficStatus, Partition36.urbanStatus)


class Partition37(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1385.6406460551018
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition37.center_x, Partition37.center_y, 200, Partition37.rainStatus, Partition37.trafficStatus, Partition37.urbanStatus)


class Partition38(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1732.0508075688772
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition38.center_x, Partition38.center_y, 200, Partition38.rainStatus, Partition38.trafficStatus, Partition38.urbanStatus)


class Partition39(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 2078.460969082653
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition39.center_x, Partition39.center_y, 200, Partition39.rainStatus, Partition39.trafficStatus, Partition39.urbanStatus)


class Partition40(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 2424.871130596428
    center_y = 1200.0

    def __init__(self):
        super().__init__(Partition40.center_x, Partition40.center_y, 200, Partition40.rainStatus, Partition40.trafficStatus, Partition40.urbanStatus)


class Partition41(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 173.20508075688772
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition41.center_x, Partition41.center_y, 200, Partition41.rainStatus, Partition41.trafficStatus, Partition41.urbanStatus)


class Partition42(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 519.6152422706632
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition42.center_x, Partition42.center_y, 200, Partition42.rainStatus, Partition42.trafficStatus, Partition42.urbanStatus)


class Partition43(Partitions):
    rainStatus = NoiseConfig.Rain13()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 866.0254037844386
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition43.center_x, Partition43.center_y, 200, Partition43.rainStatus, Partition43.trafficStatus, Partition43.urbanStatus)


class Partition44(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1212.4355652982142
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition44.center_x, Partition44.center_y, 200, Partition44.rainStatus, Partition44.trafficStatus, Partition44.urbanStatus)


class Partition45(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1558.8457268119896
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition45.center_x, Partition45.center_y, 200, Partition45.rainStatus, Partition45.trafficStatus, Partition45.urbanStatus)


class Partition46(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1905.255888325765
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition46.center_x, Partition46.center_y, 200, Partition46.rainStatus, Partition46.trafficStatus, Partition46.urbanStatus)


class Partition47(Partitions):
    rainStatus = NoiseConfig.Rain200()
    trafficStatus = NoiseConfig.OrangeTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 2251.6660498395404
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition47.center_x, Partition47.center_y, 200, Partition47.rainStatus, Partition47.trafficStatus, Partition47.urbanStatus)


class Partition48(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2598.0762113533156
    center_y = 1500.0

    def __init__(self):
        super().__init__(Partition48.center_x, Partition48.center_y, 200, Partition48.rainStatus, Partition48.trafficStatus, Partition48.urbanStatus)


class Partition49(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.GreenTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 0.0
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition49.center_x, Partition49.center_y, 200, Partition49.rainStatus, Partition49.trafficStatus, Partition49.urbanStatus)


class Partition50(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 346.41016151377545
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition50.center_x, Partition50.center_y, 200, Partition50.rainStatus, Partition50.trafficStatus, Partition50.urbanStatus)


class Partition51(Partitions):
    rainStatus = NoiseConfig.Rain50()
    trafficStatus = NoiseConfig.YellowTraffic()
    urbanStatus = NoiseConfig.MediumUrban()
    center_x = 692.8203230275509
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition51.center_x, Partition51.center_y, 200, Partition51.rainStatus, Partition51.trafficStatus, Partition51.urbanStatus)


class Partition52(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.BadUrban()
    center_x = 1039.2304845413264
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition52.center_x, Partition52.center_y, 200, Partition52.rainStatus, Partition52.trafficStatus, Partition52.urbanStatus)


class Partition53(Partitions):
    rainStatus = NoiseConfig.Rain23()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 1385.6406460551018
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition53.center_x, Partition53.center_y, 200, Partition53.rainStatus, Partition53.trafficStatus, Partition53.urbanStatus)


class Partition54(Partitions):
    rainStatus = NoiseConfig.Rain0()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.GoodUrban()
    center_x = 1732.0508075688772
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition54.center_x, Partition54.center_y, 200, Partition54.rainStatus, Partition54.trafficStatus, Partition54.urbanStatus)


class Partition55(Partitions):
    rainStatus = NoiseConfig.Rain100()
    trafficStatus = NoiseConfig.BlackTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2078.460969082653
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition55.center_x, Partition55.center_y, 200, Partition55.rainStatus, Partition55.trafficStatus, Partition55.urbanStatus)


class Partition56(Partitions):
    rainStatus = NoiseConfig.Rain150()
    trafficStatus = NoiseConfig.RedTraffic()
    urbanStatus = NoiseConfig.Rural()
    center_x = 2424.871130596428
    center_y = 1800.0

    def __init__(self):
        super().__init__(Partition56.center_x, Partition56.center_y, 200, Partition56.rainStatus, Partition56.trafficStatus, Partition56.urbanStatus)
