import math
import random
from noiseConfigGeneralAttribute import NoiseConfigGeneralAttribute

class CodeGenerator:
    def __init__(self, width, height, radius):
        self.width = width
        self.height = height
        self.radius = radius
        self.hex_height = 2 * radius
        self.hex_width = math.sqrt(3) * radius
        self.row_spacing = 0.75 * self.hex_height

    def generate_partition_class(self, index, center_x, center_y):
        rain_status = random.choice(NoiseConfigGeneralAttribute.Rain_options)
        traffic_status = random.choice(NoiseConfigGeneralAttribute.Traffic_options)
        urban_status = random.choice(NoiseConfigGeneralAttribute.Urban_options)

        class_name = f"Partition{index}"
        return f"""
class {class_name}(Partitions):
    rainStatus = {rain_status}
    trafficStatus = {traffic_status}
    urbanStatus = {urban_status}
    center_x = {center_x}
    center_y = {center_y}

    def __init__(self):
        super().__init__({class_name}.center_x, {class_name}.center_y, {self.radius}, {class_name}.rainStatus, {class_name}.trafficStatus, {class_name}.urbanStatus)
"""

    def generate_code(self):
        header = """
#this file has been generated by HexPartitionGenerator.py
         
from NoiseConfigs.noiseConfigGeneralAttribute import NoiseConfigGeneralAttribute
from noiseConfig import NoiseConfig
from typing import Optional, Dict
from utilsFunctions import UtilsFunc
import random


class Partitions:
    centerX: float
    centerY: float
    radius: float
    rainStatus: Optional[NoiseConfig.RainNoiseConfig]
    trafficStatus: Optional[NoiseConfig.TrafficNoiseConfig]
    urbanStatus: Optional[NoiseConfig.UrbanNoiseConfig]

    def __init__(self, centerX, centerY, radius, rainStatus, trafficStatus, urbanStatus):
        self.centerX = centerX
        self.centerY = centerY
        self.radius = radius
        self.rainStatus = rainStatus
        self.trafficStatus = trafficStatus
        self.urbanStatus = urbanStatus
    
    def change_rainStatus(self):
        # todo: maybe need to change this to have a more reasonable environment
        self.rainStatus = eval(random.choice(NoiseConfigGeneralAttribute.Rain_options))

    def update_traffic_status(self, traffic_statuses: Dict["Partitions", str]):
        new_status_str = traffic_statuses[self]
        self.trafficStatus = eval(new_status_str)
"""

        classes = []
        index = 1

        max_rows = int(math.ceil(self.height / self.row_spacing))
        max_cols = int(math.ceil(self.width / self.hex_width))

        for row in range(0, max_rows + 1):
            row_is_even = (row % 2 == 0)
            start_x = 0.0 if row_is_even else (self.hex_width / 2.0)

            center_y = row * self.row_spacing

            for col in range(0, max_cols + 1):
                center_x = start_x + col * self.hex_width
                classes.append(self.generate_partition_class(index, center_x, center_y))
                index += 1

        return header + "\n".join(classes)

# Example usage
width = 4300
height = 3400
radius = 200
generator = CodeGenerator(width, height, radius)
code = generator.generate_code()

with open("generated_hex_partitions.py", "w") as file:
    file.write(code)

print("Code generated and saved to generated_hex_partitions.py")
